config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  root 'welcome#index'

  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'get_user_items' => 'users#get_user_items'
  get 'craft_item' => 'users#craft_item'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :cities, controller: 'city' do
    member do
      get :citizens, :apply, :yard, :construction, :tower, :room, :hydroponics
      post :stalk, :unstalk
    end
    resources :item do
      get :push_to_city_stock, :pop_from_city_stock
      post :push_to_city_stock, :pop_from_city_stock
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :citizenships, class_name: "Citizenship",
                          foreign_key: "city_id",
                          dependent: :destroy
  has_many :citizens, through: :citizenships, source: :citizen
  has_many :buildings
  has_one :stock
  validates :name, presence: true, length: { maximum: 50 }

  # Follows a user.
  def accept(user)
    citizenships.create(citizen_id: user.id)
  end

  # Unfollows a user.
  def decline(user)
    citizenships.find_by(citizen_id: user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def citizen?(user)
    citizens.include?(user)
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  include UsersHelper
  include ItemHelper
  before_action :check_migrations, only: [:yard, :construction, :room, :tower, :hydroponics]
  before_action "logged_in_user"
  before_action "admin_user", only: [:index, :edit, :update, :destroy]
  before_action :init_places_list, only: [:show, :yard, :construction, :room, :tower, :hydroponics]
  before_action :assign_current_place, only: [:yard, :construction, :room, :tower, :hydroponics]

  def index
    @cities = City.all
  end

  def show
    if current_user.mothercity.id != @city.id
      flash[:warning] = "You have to apply citizenship of one of the cities first."
      redirect_to @user
    else
      redirect_to :action => "yard", :id => @city.id
    end
  end

  def apply
    @city = City.find(params[:id])
    @city.accept(current_user)
  end

  def yard
    @user_items = Item.where(user: current_user)
    group_stock_items(@city.stock)

    @recipes = Recipe.all
  end

  def construction
    @buildings = Building.where(city: @city)
    group_stock_items(@city.stock)
  end

  def tower
    @users = User.where(is_stalker: true)
    WebsocketRails["binder"].trigger("rebind", { new_room: "tower" })
  end

  def room
  end

  def hydroponics

  end

  def stalk
    @city = City.find(params[:id])
    current_user.is_stalker = true
    current_user.save
    notify_stalkers_changed()
    respond_stalkers()
  end

  def unstalk
    @city = City.find(params[:id])
    current_user.is_stalker = false
    current_user.save
    notify_stalkers_changed()
    respond_stalkers()
  end

  def notify_stalkers_changed
    @users = User.where(is_stalker: true)
    names = []
    for user in @users do
      names.push(user.name)
    end
    WebsocketRails["stalkers"].trigger("stalkers_list_changed", {:users => names})
  end

  private
    def check_migrations
      city = City.find(params[:id])
      if city.stock == nil
        city.stock = Stock.new
      end

      if current_user.stock == nil
        current_user.stock = Stock.new
      end
    end

    def city_params
      params.require(:user).permit(:name)
    end

    def init_places_list
      @city = City.find(params[:id])
      @places = [
        {name: "Yard", action: "yard"},
        {name: "Construction", action: "construction"},
        {name: "Watch Tower", action: "tower"},
        {name: "Room", action: "room"},
        {name: "Hydroponics", action: "hydroponics"}
      ]

    end

    def assign_current_place
      current_user.place = action_name
    end

    def respond_stalkers
      @users = User.where(is_stalker: true)
      respond_to do |format|
        format.js {}
      end
    end
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/city/_places.erb
<div class="btn-group-vertical places-group" role="group" aria-label="...">
  <% @places.each do |place| %>
    <%= link_to place[:name], "#{city_path}/#{place[:action]}", class: 'btn btn-default' %>
  <% end %>
</div>

app/views/city/_stalkers.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <p><%= user.name %></p>
    </li>
  <% end %>
</ul>

app/views/city/_stalking_actions.erb
<% if current_user.is_stalker %>
  <%= button_to 'stop stalking', unstalk_city_path(@city), class: 'btn btn-warning', :remote => true %>
<% else %>
  <%= button_to 'stalk tonight', stalk_city_path(@city), class: 'btn btn-success', :remote => true %>
<% end %>

app/views/city/apply.erb
<p>Wellcome to the <%= @city.name %> city!</p>
<%= link_to "Go there and try to survive!", @city %>

app/views/city/construction.erb
<div class="row">
  <h1>
    Construction block here, <%= current_user.name %>.
  </h1>
  <div class="col-xs-3">
    <%= render "places" %>
  </div>
  <div class="col-xs-9 items_list bordered" id="stock_items_list">
    <h3>Stock items</h3>
    <ul>
      <% @grouped_stock_items.keys.each do |item_name| %>
      <li>
        <div>
        <%= link_to city_item_pop_from_city_stock_path(@city, @grouped_stock_items[item_name][:id]), class: "pop_link", remote: true, title: item_name do %>
          <div class="item_thumbnail"><img src="/assets/thumbnails/<%= item_name %>.png" /></div>
        <% end %>
        <div class="item_amount"><%= @grouped_stock_items[item_name][:amount] %></div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-xs-3">
  </div>
  <div class="col-xs-3">
    <ul class="buildings">
      <% @buildings.each do |building| %>
        <li>
          <p><%= building.description.name %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/city/hydroponics.erb
<div class="row">
  <h1>
    You are at Hydroponics of <%= @city.name %>.
  </h1>
  <div class="col-xs-3">
    <%= render "places" %>
  </div>
</div>

app/views/city/index.erb
<div class="row">
  <div class="col-xs-4">
    <ul class="cities">
      <%= render @cities %>
    </ul>
  </div>
</div>

app/views/city/room.erb
<div class="row">
  <h1>
    You are in your room, <%= current_user.name %>.
  </h1>
  <div class="col-xs-3">
    <%= render "places" %>
  </div>
</div>

app/views/city/show.erb
<div class="row">
  <h1>
    Welcome to <%= @city.name %>.
  </h1>
</div>

app/views/city/stalk.js.erb
$('#stalking_actions').html("<%= j (render 'stalking_actions') %>");

app/views/city/tower.erb
<% content_for :javascript_includes do %>
  <!--<%= javascript_include_tag 'js_file_to_include_here' %>-->
<% end %>

<div class="row">
  <h1>
    You are at Watch Tower of <%= @city.name %>.
  </h1>
  <div class="col-xs-3">
    <%= render "places" %>
  </div>
  <div class="col-xs-6" id="stalkers_list">
    <h3>Users who are stalking tonight</h3>
    <%= render "stalkers" %>
  </div>
  <div class="col-xs-3" id="stalking_actions">
    <%= render "stalking_actions" %>
  </div>
</div>

app/views/city/unstalk.js.erb
$('#stalking_actions').html("<%= j (render 'stalking_actions') %>");

app/views/city/yard.erb
<div class="row">
  <h1>
    You are in the Yard of <%= @city.name %>.
  </h1>
  <div class="col-xs-3 bordered">
    <%= render "places" %>
  </div>
  <div class="col-xs-3 items_list bordered" id="user_items_list">
    <h3>Your items</h3>
    <ul>
    </ul>
    <script>$.ajax('<%= get_user_items_path %>')</script>
  </div>
  <div class="col-xs-3 bordered"></div>
  <div class="col-xs-3 items_list bordered" id="stock_items_list">
    <h3>Stock items</h3>
    <ul>
      <% @grouped_stock_items.keys.each do |item_name| %>
      <li>
        <div>
        <%= link_to city_item_pop_from_city_stock_path(@city, @grouped_stock_items[item_name][:id]), class: "pop_link", remote: true, title: item_name do %>
          <div class="item_thumbnail"><img src="/assets/thumbnails/<%= item_name %>.png" /></div>
        <% end %>
        <div class="item_amount"><%= @grouped_stock_items[item_name][:amount] %></div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-xs-3"></div>
  <div class="col-xs-2 craft_slot bordered" id="craft_slot_1"></div>
  <div class="col-xs-2 craft_slot bordered" id="craft_slot_2"></div>
  <div class="col-xs-2 craft_slot bordered" id="craft_slot_3"></div>
  <div class="col-xs-2">
    <%= link_to "Clear Slots", "#", class: "btn-s btn-danger", onclick: "clearCraftingSlots()", remote: true %>
    <%= link_to "Craft", "#", class: "btn-s btn-success", onclick: "craftItem()", remote: true %>
  </div>
</div>