config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  root 'welcome#index'

  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'get_user_items' => 'users#get_user_items'
  get 'craft_item' => 'users#craft_item'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :cities, controller: 'city' do
    member do
      get :citizens, :apply, :yard, :construction, :tower, :room, :hydroponics
      post :stalk, :unstalk
    end
    resources :item do
      get :push_to_city_stock, :pop_from_city_stock
      post :push_to_city_stock, :pop_from_city_stock
    end
  end
end

app/views/layouts/_flash.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.erb
<nav class="navbar navbar-fixed-bottom">
  <p>gordev&nbsp;&nbsp;&nbsp;[&nbsp;<a href="email:zaynyatyi@gmail.com">zaynyatyi@gmail.com</a>&nbsp;]</p>
</nav>

app/views/layouts/_header.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Telezda</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li><%= link_to current_user.name, current_user %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_whoops_alert.erb
<!-- Modal -->
<div id="whoopsModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Whoops!</h4>
      </div>
      <div class="modal-body">
        <p>Something gone wrong. Press OK to reload page.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="window.location.reload();">OK</button>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TelezdaLite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascript_includes %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% if logged_in? %>
      <%= content_tag :div, :id => "place_holder", :data => {:place => current_user.place} do %><% end %>
    <% end %>
    <div id="flashes_container">
      <%= render 'layouts/flash' %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/whoops_alert' %>
  </div>

</body>
</html>